### ISSUE TITLE
Error building while using postdeploy script and include sub-scripts

### ISSUE THREAD

**Issue by pada57** [rr-wfm/MSBuild.Sdk.SqlProj#103]
Hello

i'm having issue to setup project which contains pre/post deployment "sub" scripts included via syntax ":r" or "r:"

```
PRINT 'Permissions...'
GO
r: PostDeployment.GrantPermissions.sql
GO
--PRINT 'Seed data...'
--GO
r: Seeds/_seeds.sql
```

Getting those kind of errors
```
EXEC : warning SQL70501: DML statements cannot be modeled. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
EXEC : error SQL46010: Incorrect syntax near PostDeployment. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
EXEC : error SQL46010: Incorrect syntax near Seeds. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
C:\Users\foo\.nuget\packages\msbuild.sdk.sqlproj\1.10.0\Sdk\Sdk.targets(196,5): error MSB3073: The command "dotnet "C:\Users\foo\.nuget\packages\msbuild.sdk.sqlproj\1.10.0\Sdk\../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj\Debug\netstandard2.0\API.Database.dacpac" -n "API.Database" -v "1.0.0" -sv Sql130 -i "obj\Debug\netstandard2.0\API.Database.InputFiles.txt"  -sc MySqlCmdVariable -p RecoveryMode=Simple  --postdeploy Scripts\PostDeployment.sql  " exited with code 1. [C:\Users\foo\Documents\svn\play\SSDT\API.Database\API.Database.csproj]
    1 Warning(s)
    3 Error(s)
```

I tried syntax ":r" and got `EXEC : error SQL46010: Incorrect syntax near :.

Here my csproj file
```
<Project Sdk="MSBuild.Sdk.SqlProj/1.10.0">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SqlServerVersion>Sql130</SqlServerVersion>
    <CompatibilityMode>130</CompatibilityMode>
    <RecoveryMode>Simple</RecoveryMode>
    <BackupDatabaseBeforeChanges>True</BackupDatabaseBeforeChanges>
    <BlockOnPossibleDataLoss>True</BlockOnPossibleDataLoss>
    <AnsiNulls>True</AnsiNulls>
    <QuotedIdentifier>True</QuotedIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <!--<Content Remove="Scripts\PostDeployment.sql" />-->
    <PostDeploy Include="Scripts\PostDeployment.sql" />
    <Content Remove="Scripts\PostDeployment.GrantPermissions.sql" />
    <Content Remove="Scripts\identity.sql" />
    <Content Remove="Scripts\identity-live.sql" />
    <Content Remove="Scripts\Changes\**" />
    <Content Remove="Scripts\Seeds\**" />
  </ItemGroup>
  <ItemGroup>
    <SqlCmdVariable Include="InitialLoad">
      <DefaultValue>FALSE</DefaultValue>
      <Value>$(InitialLoad)</Value>
    </SqlCmdVariable>
  </ItemGroup>
</Project>
```

**Comment by jmezach** [comment]
@pada57 Thanks for getting in touch. Based on the errors it seems that your post deployment script is being included as part of the build which is not supported. I noticed a `<Content Remove="..." />` element in your project file that was commented out. I think you'll need to uncomment that.

If that still doesn't work could you share the full build output? That would give us some more to go on.

**Comment by pada57** [comment]
> @pada57 Thanks for getting in touch. Based on the errors it seems that your post deployment script is being included as part of the build which is not supported. I noticed a `<Content Remove="..." />` element in your project file that was commented out. I think you'll need to uncomment that.
> 
> If that still doesn't work could you share the full build output? That would give us some more to go on.

I commented as I had before remove postdeployment.sql script and then build pass but with no postdeploy in dacpac. I then use postdeploy tag element and got this error due to sqlcmd lines it seems, is it supported?
When I remove :r or r: then it passed build but without including subscripts
I use that in ssdt project without issue

**Comment by jmezach** [comment]
You'll need to have both the `<Content Remove="" />` and `<PostDeploy Include="" />` elements in your project file. The first one ensures that the script will not be included in the build process and the second one makes sure that the script is included as a post deployment script. The reason you need both is that by default we include all `.sql` files in all folders except for the `Pre-Deployment` and `Post-Deployment` folders. Since you're post deployment script is in a `Scripts` folder it is not excluded by default.

You should be able to include other scripts using the `:r <script>` syntax with the version of MSBuild.Sdk.SqlProj you appear to be using.

**Comment by pada57** [comment]
> You'll need to have both the `<Content Remove="" />` and `<PostDeploy Include="" />` elements in your project file. The first one ensures that the script will not be included in the build process and the second one makes sure that the script is included as a post deployment script. The reason you need both is that by default we include all `.sql` files in all folders except for the `Pre-Deployment` and `Post-Deployment` folders. Since you're post deployment script is in a `Scripts` folder it is not excluded by default.
> 
> You should be able to include other scripts using the `:r <script>` syntax with the version of MSBuild.Sdk.SqlProj you appear to be using.

Yes works ! thanks a lot @jmezach 

i like dotnet publish compare to sqlpackage.exe. Does it support to give a publish file as parameter ?

i have issue when setting option to drop objects not in source and trying to preserve security objects for instance Users
```
 dotnet publish /p:TargetDatabaseName=API_clean /p:DropObjectsNotInSource=True /p:DoNotDropUsers=True
...
Setting property BackupDatabaseBeforeChanges to value True
  Setting property BlockOnPossibleDataLoss to value True
  Setting property DropObjectsNotInSource to value True
  Setting property IncludeCompositeObjects to value true
  Setting property ScriptDatabaseOptions to value False
  Adding SQLCMD variable 'InitialLoad' with value 'NO'
...
 Dropping Permission...
  Dropping Permission...
  Dropping Permission...
  Dropping <unnamed>...
...
```

i can use sqlpackage if not supported yes as dacpac is produced.
Great work guys, i really appreciate this project as i want to get away merge hells issue with sqlproj files and use modern CLI like on other dotnet core projects
i will perhaps try to contribute if i can :)

**Comment by jmezach** [comment]
@pada57 First of all thanks for the encouragement, that means a lot!

As for your questions, I'm not sure what you mean with publish file? Do you mean that you'd like to have support for generating the script that is run? I believe there is an open issue for generating a script to create the database from scratch, but that will not do a compare to an existing database so might not be what you're after.

We currently feel that dotnet publish is geared towards deploying your database during development and not the best tool for deploying to test and/or production systems. We recommend using SqlPackage.exe for that since it supports more scenarios already. But if you feel that this is important for you feel free to open a separate issue for that and explain your scenario.

As for the objects being dropped I'm not quite sure why that happens. Does it also happen when using SqlPackage.exe with the same parameters? If so than it might be a bug and I would suggest opening a separate issue for that.

@ErikEJ @jeffrosenberg Should we explain the original issue here better in the docs perhaps? Not the first time this has come up I believe.

**Comment by pada57** [comment]
> As for your questions, I'm not sure what you mean with publish file? Do you mean that you'd like to have support for generating the script that is run?

More talking about using like for sqlpackage.exe a publish file which contains all props for a deployment avoiding having to enter on CLI all parameters which are very long with preserve instructions.
```
"%env.sqlpackage%" /Action:Publish /SourceFile:"<db>.dacpac" /pr:<publishfile>.xml
```
i will use sqlpackage as you said for time being for managed environments

>As for the objects being dropped I'm not quite sure why that happens. Does it also happen when using SqlPackage.exe with the same parameters?
No it doesn't happen but parameters are different since sending params for each do NOT drop flag
```<DoNotDropRoleMembership>True</DoNotDropRoleMembership>
    <DoNotDropRoutes>True</DoNotDropRoutes>
    <DoNotDropRules>True</DoNotDropRules>
    <DoNotDropUsers>True</DoNotDropUsers>
    <DoNotDropSignatures>True</DoNotDropSignatures>
```
i can open second issue if you want and you can close this one 👍

**Comment by jmezach** [comment]
Yes, please open a separate issue for that. As for the publish profile that is currently not supported and I don't think we'll be adding that. If you want to avoid having to type them every time you run dotnet publish you can set them in the project file if you want.

**Comment by pada57** [comment]
> Yes, please open a separate issue for that. As for the publish profile that is currently not supported and I don't think we'll be adding that. If you want to avoid having to type them every time you run dotnet publish you can set them in the project file if you want.

yes thought about that but as can be different from environments. I don't like to mix build and publish props
Thanks for all

**Comment by ErikEJ** [comment]
I kind of wish that the "publish" feature was not added, so the project can focus its effort on building .dacpacs - there are so many things sqlpackage can do that it will be impossible to catch up.

So in my opinion, anything that does not work in the current implementation should be referred to sqlpackage.

**Comment by jmezach** [comment]
@ErikEJ I agree. I feel that we added publish support purely to support developers who need to quickly deploy their changes to a local SQL Server instance so that they can test them. But perhaps we can make that explicit in the README and refer to SqlPackage for more advanced scenario's. Hopefully that avoids a couple of questions.

**Comment by jeffrosenberg** [comment]
Yup, I agree as well. In my mind, the big distinction is that the rest of the project provides support for missing functionality on non-Windows systems, while SqlPackage works on those same systems today, so there's no gap to be filled.
