### ISSUE TITLE
Posibility to run post-deployment scripts of dependencies

### ISSUE THREAD

**Issue by verhoofstad** [rr-wfm/MSBuild.Sdk.SqlProj#110]
Can it be possible to run the pre- and post deployment scripts of your dependencies too?

**Comment by jeffrosenberg** [comment]
This is already possible in a somewhat roundabout way; I do this today in some of my projects.

The pre- and post-deployment scripts allow includes of other files, which can be used to reference the scripts of your dependencies. I would typically couple this with a sqlcmd variable for the dependency path, so it doesn't need to be hardcoded, which could be brittle.

**Comment by jmezach** [comment]
@jeffrosenberg Interesting. But doesn't that mean that you'd need to have the source code of the referenced project on your local machine as well? That feels kind of heavy since you already have the `.dacpac` of the referenced project there.

I was actually thinking of making this a feature of `MSBuild.Sdk.SqlProj`. I totally understand why `SqlPackage.exe` doesn't do this, because you'd want to deploy each `.dacpac` separately through its own pipeline. But at development time I can see value in us running the `predeploy.sql` and `postdeploy.sql` of referenced projects as well. Ideally this would of course be configurable. I was thinking of throwing something together this weekend ;).

**Comment by jeffrosenberg** [comment]
@jmezach my use case was for working with SqlPackage, so yeah, that's somewhat different than what you're proposing. I have to admit, I'm not totally sure what this would look like, but interested to see what you come up with! 🙂

**Comment by jmezach** [comment]
I've started some initial work on this in the `feature/pre-post-dependencies` branch. It is already working fairly well for our test projects, but it needs a bit more work. Most notably we'll need to supply some default SQLCMD variables (for example: `DatabaseName`) as users will probably expect those to be set.

We might also need to figure out what SQLCMD variables have been defined by the referenced package (which requires them to be present in that package in the first place, which we currently do not do I think) and figure out a way to define their values as well. Not sure if users just expect that to work out of the box though.

**Comment by ErikEJ** [comment]
The SQLcmd variables issue could be as reason why this is not available with sqlproj?

**Comment by jmezach** [comment]
@verhoofstad A [pre-release version](https://www.nuget.org/packages/MSBuild.Sdk.SqlProj/1.11.0-beta.16.g9a5ba98c5e) of MSBuild.Sdk.SqlProj is up on NuGet.org. Could you give that a spin to see if it resolves our issue? You will need to update the SDK version number in the `.csproj` and also add the new `RunScriptsFromReferences` property to it.

**Comment by jmezach** [comment]
@verhoofstad A stable release is now available on NuGet.org.
