### ISSUE TITLE
Adding package reference to DACPAC project does not result in .dacpac file being copied to bin directory

### ISSUE THREAD

**Issue by flakey-bit** [rr-wfm/MSBuild.Sdk.SqlProj#117]
In my solution (simplified) I have two projects:
- `Some.Namespace.Database` - this is the `MSBuild.Sdk.SqlProj` SDK project for producing the DACPAC
- `Some.Namespace.DataAccess` - this is a vanilla `Microsoft.NET.Sdk` (`netstandard2.0`) project containing C# data access code

I've added a project reference from `Some.Namespace.DataAccess` to  `Some.Namespace.Database` as follows:

```
  <ItemGroup>
    <ProjectReference Include="..\Some.Namespace.Database\Some.Namespace.Database.csproj" />
  </ItemGroup>
```

When I build `Some.Namespace.Database` it produces the `.dacpac` file in the output directory for that project, however when I build `Some.Namespace.DataAccess` I was hoping/expecting the `.dacpac` file to be copied to the output directory for _that_ project, since it's a dependency.

Is there any easy way to achieve what I want? NB use-case is around programatically loading the DACPAC file via `DacServices` / `DacPackage.Load` in `Microsoft.SqlServer.Dac` (NuGet package [Microsoft.SqlServer.DacFx.x64](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x64/))

NB: I tried changing `Some.Namespace.DataAccess` to a concrete framework (`netcoreapp3.1`) however that didn't help 😢

**Comment by jmezach** [comment]
@flakey-bit This isn't currently build in unfortunately. In fact I'm even surprised that it builds at all because I would expect your project `Some.Namespace.DataAccess` to not compile since it would try to include a reference to the `.dacpac` file which obviously doesn't work.

That being said I do think this could be a reasonable scenario to support. According to the docs for the [project reference protocol](https://github.com/dotnet/msbuild/blob/master/documentation/ProjectReference-Protocol.md) we might be able to implement a `GetCopyToOutputDirectoryItems` target that would return the `.dacpac` which should then copy that file to the output directory.

If you're adventurous we would appreciate a PR for this. Not sure when we'll have time to implement this.

**Comment by ErikEJ** [comment]
A post build step could maybe also work?

**Comment by AroglDarthu** [comment]
This one was interesting... @jmezach is correct with his assumption that the project does not compile. However this can be achieved by adding `<ReferenceOutputAssembly>False</ReferenceOutputAssembly>`:
```
  <ItemGroup>
      <ProjectReference Include="..\Some.Namespace.Database\Some.Namespace.Database.csproj">
        <ReferenceOutputAssembly>False</ReferenceOutputAssembly>
      </ProjectReference>
  </ItemGroup>
```
