### ISSUE TITLE
TreatTSqlWarningsAsErrors not used

### ISSUE THREAD

**Issue by AroglDarthu** [rr-wfm/MSBuild.Sdk.SqlProj#185]
Hi Jonathan,

Just started using your awesome SDK v1.16.2 :-)
Kudos to you and all contributors; what an awesome gem.

I ran into a quirk. Our solution uses `Directory.Build.props` to set `TreatWarningsAsErrors` to `True`.
It seems that this trumps the project setting `<TreatTSqlWarningsAsErrors>False</TreatTSqlWarningsAsErrors>`.  It's a different property, I know, but both result in adding or omitting the `--warnaserror` argument. As the project now indicates it should be omitted, I did not expect to find it on the command line.

The workaround was easy enough: set `TreatWarningsAsErrors` on project level to `False`.

Perhaps you are planning on deprecating `TreatTSqlWarningsAsErrors` in favour of `TreatWarningsAsErrors`?
Either way, I believe that as long as `TreatTSqlWarningsAsErrors` is supported at project level, it should override `TreatWarningsAsErrors` from higher up.

**Comment by jmezach** [comment]
@AroglDarthu First of all, thank you for the encouragement. Really appreciate it!.

As for your question, I remember that when we build this we said we should support both `TreatTSqlWarningsAsErrors` as well as `TreatWarningsAsErrors` so that you could use either and it would work in the same way. You can see that in the code [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/87743947b94b08036b7c5aabda5d3abe3681bae6/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets#L219). So basically we check if `TreatTSqlWarningsAsErrors` is a `True` first and if it is not we'll also check `TreatWarningsAsErrors` and if that is `True`, and then and only then will we add the `--warnaserror` flag.

From what I understand from your question you want to have the ability to set `TreatWarningsAsErrors` for all your projects to `True`, but set `TreatTSqlWarningsAsErrors` to `False` for your database project specifically so that `TreatWarningsAsErrors` doesn't apply to that specific project? Is that correct?

**Comment by AroglDarthu** [comment]
@jmezach Yes, that's the jist of it.

The readme lead me to `TreatTSqlWarningsAsErrors` and I set it to `False`. I didn't give it any thought that the `Directory.Build.props` already forced a solution wide `TreatWarningsAsErrors=True`. So, when I still received errors it took me some time to realize what was going on. Luckily the following note in the readme put me on the right track:
> Note: Alternatively one can use TreatWarningsAsErrors instead of TreatTSqlWarningsAsErrors to apply the same effect.

However, project level should always win (IMHO).

I can confirm that setting `TreatWarningsAsErrors=False` on solution level _loses_ from setting `TreatTSqlWarningsAsErrors=True` at project level. But in the same manner, `TreatWarningsAsErrors=True` on solution level should _lose_ from `TreatTSqlWarningsAsErrors=False` at project level.

**Comment by jmezach** [comment]
Yeah, that's probably because we only check for the `True` case, but never for the `False` case. That makes sense if you only look at a single property, but with multiple properties that becomes a bit of a problem. Perhaps we should change the condition so that `TreatWarningsAsErrors=True` only does something if `TreatTSqlWarningsAsErrors` is not set (ie. empty). I believe that would solve your scenario.
