### ISSUE TITLE
Generated create script does not set TargetDatabaseName

### ISSUE THREAD

**Issue by AroglDarthu** [rr-wfm/MSBuild.Sdk.SqlProj#186]
The property `TargetDatabaseName` _Controls the name of the database published by dotnet publish_.
I expected the generated create script to use that property's value for `:setvar DatabaseName` as well.
Unfortunately it does not, it uses the project name instead.

**Comment by jmezach** [comment]
I had a quick look at this and by the looks of it this is because the script generation is part of the `build` phase rather than the `publish` phase. So we currently don't look at the value of `TargetDatabaseName` at all when building the project.

I guess we could fix that by passing the value of the property to the `DacpacTool` if it is set during build as well and then the `DacpacTool` could use that if `GenerateCreateScript` is set to `True` as well.

Not sure when I'll have the time to implement that though, but feel free to sent in a PR.
