### ISSUE TITLE
Unknown target framework moniker

### ISSUE THREAD

**Issue by AroglDarthu** [rr-wfm/MSBuild.Sdk.SqlProj#192]
https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/e57fc2470b80ac277d2ccaf6b1336580ec3c88c9/src/DacpacTool/DacpacTool.csproj#L5

`netcoreapp5.0` should be `net5.0`
The test project targets net5.0. In Visual Studio that leads to the error message:
> Project '..\..\src\DacpacTool\DacpacTool.csproj' targets 'netcoreapp2.1;netcoreapp3.1;netcoreapp5.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v5.0'.

**Comment by jmezach** [comment]
Hmm, I believe that `netcoreapp5.0` and `net5.0` are actually synonymous. The reason we're using `netcoreapp5.0` is because of [this check](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/master/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets#L92).

I haven't had any problems with it so far to be honest, although I haven't opened the solution in Visual Studio at all. I usually use VS Code which doesn't seem to have any issues with it.

**Comment by AroglDarthu** [comment]
You could be right in that `netcoreapp5.0` _can_ still be used. The error that I got, made me look for it in the docs. The moniker `netcoreapp5.0` is no longer official: https://docs.microsoft.com/en-us/dotnet/standard/frameworks

On the bright side: I got the error because of a newer .NET5 SDK and an old(er) version of Visual Studio.

The following line will also need to be changed:
https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/e57fc2470b80ac277d2ccaf6b1336580ec3c88c9/src/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj.csproj#L34

And then of course the line you mentioned (and the error message below it) should use `MicrosoftNETBuildTasksTFM` which translates to `netcoreapp2.1` or `netcoreapp3.1` or `net5.0`.

**Comment by jmezach** [comment]
I wonder how long `MicrosoftNETBuildTasksTFM` has been there. I remember looking for something like that but I wasn't able to find it. I guess we could try changing the logic to depend on that property instead of `BundledNETCoreAppTargetFrameworkVersion` and then see what CI thinks of that. We already build with different versions of the SDK anyway, so if older versions didn't have it it would probably fail ;).

**Comment by AroglDarthu** [comment]
I edited my comment above. Turns out SDK 2.1 sets `$(MicrosoftNETBuildTasksTFM)` to `netstandard2.0`.
Bummer.

**Comment by jmezach** [comment]
I guess it is time to drop support for .NET Core 2.1 anyway since it has gone out of support anyway.

**Comment by jmezach** [comment]
I'm thinking that maybe we should do a 2.0 release in which we drop support for .NET Core 2.1 (since it is out of support) and add support for .NET 6 (since that is now Go Live) and include all of the other changes and include this change as well. For people that are still on .NET Core 2.1 they can stick with version 1.16 for now, but my guess is that most people use at least 3.1 so they can easily upgrade to 2.0.

@jeffrosenberg @ErikEJ What do you think?

**Comment by ErikEJ** [comment]
Good idea, maybe it should stay as 2.0-preview until 6.0 RTM?

**Comment by jmezach** [comment]
Yeah, that makes sense.

**Comment by jeffrosenberg** [comment]
Sounds good to me!

**Comment by AroglDarthu** [comment]
https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/addbf26c69f00a2faaae71e3d993636d75772f69/version.json#L3
Does the pipeline change this automatically, or can I just replace this with `2.0-beta`?

**Comment by jmezach** [comment]
Yeah, that should probably be updated to be `2.0.0-beta.{height}`. It is used by the pipeline to calculate the final version number automatically.

**Comment by AroglDarthu** [comment]
I can get the `MSBuild.Sdk.SqlProj` itself to build nicely for target  framework `net6.0`.
However, building one of the test projects while using the net6.0 SDK fails with the following message:
```
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Using target framework net6.0 to run DacpacTool
  Using package name TestProject and version 1.0.0
  Setting property ServiceBrokerOption to value EnableBroker
  Setting property RecoveryMode to value Simple
  Setting property AllowSnapshotIsolation to value True
  Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.PlatformNotSupportedException: Strong-name signing is not supported on this platform.
     at System.Reflection.AssemblyName.get_KeyPair()
     at Microsoft.Data.Tools.Schema.Extensibility.ExtensionTypeLoader.ExtensionAssemblies.CreateAssemblyName(String partialName, AssemblyName templateName)
```

**The command leading to this exception:**
> /Sdk.targets(228,5): error MSB3073: The command "dotnet "/Sdk/../tools/net6.0/DacpacTool.dll" build -o "obj/Debug/netstandard2.0/TestProject.dacpac" -n "TestProject" -v "1.0.0" -sv Sql150 -i "obj/Debug/netstandard2.0/TestProject.InputFiles.txt"   -p ServiceBrokerOption=EnableBroker -p RecoveryMode=Simple -p AllowSnapshotIsolation=True         " exited with code 1.

Adding a `global.json` to force `SDK 5.0.401` resolves the issue, so I find it reasonable to assume that the problem is related to using the current net6.0 SDK.

Any ideas on how to solve this?

**Comment by jmezach** [comment]
That's an interesting error. I thought .NET Core has never supported strong-name signing, but perhaps they've only started throwing exceptions when trying to use it with .NET 6.

Do we know where this occurs in our code? The `TargetInvocationException` suggests this is coming from some code that we're calling through reflection. This sounds like an issue in the DacFx assembly, so maybe we can file that [here](https://github.com/microsoft/DacFx/issues).

**Comment by AroglDarthu** [comment]
I've asked about it here: https://github.com/dotnet/core/issues/6688#issuecomment-921204627
Let's see what comes back...

**Comment by KalleOlaviNiemitalo** [comment]
The MSBuild fix <https://github.com/dotnet/msbuild/pull/6395> modified only the Microsoft.Build.BackEnd.TranslatorHelpers class, which also appeared in the stack trace in <https://github.com/dotnet/msbuild/issues/6389>. Because your stack trace does not include that class, I don't think the MSBuild fix can help solve this issue.

**Comment by AroglDarthu** [comment]
I'm afraid you are correct.

**Comment by jmezach** [comment]
I really think this is an issue in DacFx and has to be fixed there. Unfortunately that isn't open source yet. But they do have a repo for filing issues [here[(https://github.com/microsoft/DacFx/issues).

**Comment by jmezach** [comment]
See Microsoft/DacFx#33

**Comment by jmezach** [comment]
It seems that the 16.x preview release of DACFX solves the issue, so that's the good news. Unfortunately it seems that we can't use `MicrosoftNETBuildTasksTFM` to reliably determine the correct version of DacpacTool to run either since it is set to `netcoreapp2.1` even for the .NET 3.1 SDK release (see [here](https://github.com/dotnet/sdk/blob/ecb565f587197795e3855c765d51c513a7a3a62f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets#L18)) for which we're trying to drop support.

**Comment by jmezach** [comment]
So I've gone back to using `BundledNETCoreAppTargetFrameworkVersion` and then special casing .NET Core 3.1 to use `netcoreapp` as the prefix, while for other versions we use `net` as the prefix. Since we're dropping support for .NET Core 2.1 I think that'll be fine for now. I guess we could remove it again once 3.1 goes out of support.
