### ISSUE TITLE
Help setting up a debugging environment 

### ISSUE THREAD

**Issue by brandonmcclure** [rr-wfm/MSBuild.Sdk.SqlProj#26]
I am testing out the feasibility of using this SDK to convert our existing SSDT projects. I can setup a blank new project with no problems, but when I try to import all of our sql files from one of our existing projects I get an error: 
```
Determining projects to restore...
  All projects are up-to-date for restore.
  The system cannot execute the specified program.
C:\Users\bmcclure\.nuget\packages\msbuild.sdk.sqlproj\1.1.0\Sdk\Sdk.targets(153,5): error MSB3073: The command "dotnet 
```
Followed by a lot of text. This project has ~1400 sql files in the folder structure, so I removed a bunch of files (1000) to try a build with fewer files. This appears to be actually running msbuild, and is now throwing errors and I can see from the stack trace that these are getting thrown from this sdk nuget:

```
 Unable to find input file C:\xxxx\LoadDiagnosiFileTable.sql (Parameter 'inputFile')
     at MSBuild.Sdk.SqlProj.BuildDacpac.PackageBuilder.AddInputFile(FileInfo inputFile) in /home/runner/work/MSBuild.Sdk.SqlProj/MSBuild.Sdk.SqlProj/src/BuildDacpac/PackageBuilder.cs:line 60
```

I can infer some stuff from this error message, and I can read the code at this line, but what I would like to do is setup a breakpoint in VS and run `dotnet build` and force dotnet/nuget to use my local build instead of the version from nuget so I can debug/step through why this is failing so that I can make better issues/contributions to this code. This dotnet sdk development is new to me, do you have any suggested reading/links that could help put me on the right track for developing/debugging this?

**Comment by jmezach** [comment]
Hi @brandonmcclure. First of all, thanks for giving it a try. The first error you posted seems to suggest that it wasn't able to find the dotnet command line tool, which is part of the .NET Core SDK. Can you verify that you have this installed?

I'm assuming you have though since it does seem to work fine with fewer files. Maybe there is a limit on the number of arguments you can pass into a command line tool which is causing the first error. Every SQL file that is part of the project is passed as a command line argument individually, so with 1400 files you'd get 1400 arguments. I can have a look at that, but I'm not sure if there's much we can do about it. What OS are you running this on?

As for setting up a debugging environment, you can have a look at the [test project](https://github.com/jmezach/MSBuild.Sdk.SqlProj/blob/master/test/TestProject/TestProject.csproj). This project doesn't import the NuGet package (using `<Project Sdk="MSBuild.Sdk.SqlProj/1.1.0">`), but imports the locally build version of the Sdk directly (using `<Import Project="...">` elements). You can do the same in your own project file and point it at your local clone of the repository. Note that you'll need both `<Import>` elements and they need to be at the start and the end of the project file, just like the test project. Also make sure that you remove the `Sdk` attribute from the `<Project>` element.

Then you'll probably want to put a `System.Diagnostics.Debugger.Launch()` statement somewhere in the `BuildDacpac` tool and then run a `dotnet build` command in the `src\MSBuild.Sdk.SqlProj` folder. If you then compile your project you should get a popup asking you if you want to attach a debugger.

Good luck and if you have any more questions, don't hesitate to reply to this issue. Also, let me know if what I've described above works. I should probably add that to the CONTRIBUTING.md or something.

**Comment by brandonmcclure** [comment]
Thanks @jmezach that helps me get started. I am running Windows 10. My .net sdk seems to be working, since I can build other (asp core) projects and a more simplified existing SSDT project. 

I don't have the debugger setup yet, but plan on working on this in the next week or 2 and will share how that goes. 

We have several databases that we manage through several somewhat monolithic SSDT projects. When we started this work we went with monolithic projects because we thought it would be too difficult for our developers to remember which solution/project has their code base in them, and to be honest we did not have a very solid deployment platform and the overhead of many projects was too much for us.

A few years later and our deployment is much more solid, and our devs are comfortable with doing their database work in a managed way and are now concerned about the speed that they can get their code deployed. Our goal with this sdk is to be split these SSDT projects into smaller builds in a seamless way so that the developers just keep working with their object definitions in .sql files, and our build system handles the complexity of deploying the correct changes. My idea is to powershell out `MSBuild.Sdk.SqlProj` project for each schema, so we will end up with many much smaller projects :-)

**Comment by jmezach** [comment]
I hink that's actually a very good use case for using this project. We have been doing that as well, splitting out a huge monolithic database project into smaller pieces. But with the lack of support for using NuGet packages in .sqlproj files it is a rather frustrating experience. But with MSBuild.Sdk.SqlProj this is really easy to do.

**Comment by jmezach** [comment]
Hi @brandonmcclure. Just checking in to see if you've managed to validate [my hypothesis](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/26#issuecomment-649240746)?

**Comment by brandonmcclure** [comment]
@jmezach, thanks for the follow up. That did work, I was able to connect the debugger and step through the build.

**Comment by jmezach** [comment]
Ah cool! That's great to hear. I'll leave this issue open so that we can add this to a CONTRIBUTING.md for any folks needing to do the same thing in the future.

**Comment by jmezach** [comment]
I've just added a contribution guide to the repository including the note about debugging locally.
