### ISSUE TITLE
[Question] Is there any plan to add unit testing capabilities to this project?

### ISSUE THREAD

**Issue by freddie2025** [rr-wfm/MSBuild.Sdk.SqlProj#452]
In the SSDT project, we had the ability to unit test our database code using the following library: `Microsoft.Data.Tools.Schema.Sql.UnitTesting`. Is there any plan to offer a .net core equivalent?

**Comment by jmezach** [comment]
We don't currently have plans to add it, since we are not actively using this ourselves nor do we have any experience with it. If someone is willing to contribute it though, we'd be happy to integrate it.

Alternatively something like this might come to Microsoft's own offering that they are working on, but I'm not sure if it is on the roadmap. Have a look at https://github.com/microsoft/dacfx for more details on that.
