### ISSUE TITLE
How to reference sql scripts from nuget in Post Deployment Script

### ISSUE THREAD

**Issue by csabaantoni** [rr-wfm/MSBuild.Sdk.SqlProj#463]
We have one MSBuild.Sdk.SqlProj project (DB.A) wich contains sql scripts too for data population .
How to include these scripts into nuget package in order to be able to reference these scripts in post deployment script of the other MSBuild.Sdk.SqlProj project (DB.B)?

Earlier in our old approach, DB.B referenced DB.A sqlproj and in post deployment script we used references like this: 
r: ..\DB.A\Scripts\scriptA.sql

How to accomplish this via nuget package?

Thanks,
Toni

**Comment by jmezach** [comment]
I guess yo could add the SQL scripts to your NuGet package by tweaking your `.nuspec` file to include them. But then you'd have to figure out the path where the package is stored from your post deployment script in order to reference it. There's probably a way to do that, but I'm not sure what the best way would be.

Perhaps adding some context here can help so we can figure out the best solution to your problem. What are you trying to achieve?

**Comment by ErikEJ** [comment]
@csabaantoni Closing this due to lack of response - maybe a linked item could work for you?
