### ISSUE TITLE
Referencing projects through `.sqlproj` files

### ISSUE THREAD

**Issue by antoine-coulon** [rr-wfm/MSBuild.Sdk.SqlProj#486]
Hello,

I'm currently searching for a way of linking different SQL projects together, that is having something like

```
/main-app
  /database
     main.sqlproj

/some-shared-module
   /database
      shared.sqlproj
```

Where `main.sqlproj` references `shared.sqlproj` defining a set of shared tables and other database elements that should be created within the `main-app` database.

I noticed from the "Project References" documentation section that **"We do not support adding a ProjectReference to an existing .sqlproj file."**.

Consequently what are the other ways to achieve that only using `.sqlproj` project (with only SQL definitions) without relying on NuGet nor C# projects? We are currently not using these tools and we would just want to rely on `.sqlproj` definitions to create these project references.

Thanks

**Comment by jeffrosenberg** [comment]
Hi @antoine-coulon - I think you're looking in the wrong place! We don't support project references to .sqlproj files because we don't use those sorts of files in our SDK. You mentioned that you're currently not using C# projects or NuGet, but if that's the case it means that you're not using our SDK, so our documentation isn't relevant to you! 🙂 

I believe SSDT does support this feature. Check out the documentation for [composite projects](https://learn.microsoft.com/en-us/sql/ssdt/add-database-reference-dialog-box?view=sql-server-ver16#to-create-a-composite-project).

**Comment by antoine-coulon** [comment]
Hello @jeffrosenberg thanks for clarifying that! I didn't get the package right then I'm actually sorry about that. I thought it was basically a wrapper of SSDT (that I could still build and deploy using .NET CLI) that was adding other C# features but it is indeed only a C# SDK 😅

Sorry for wasting your time and thanks for taking the time to provide me the appropriate pointer to the SSDT documentation.

Closing the issue as my question is not relevant to `MSBuild.Sdk.SqlProj`
