### ISSUE TITLE
SqlServerVersion

### ISSUE THREAD

**Issue by brettrowberry** [rr-wfm/MSBuild.Sdk.SqlProj#86]
I find it difficult to figure out what to put as the value for `<SqlServerVersion>` in the project file. 

Let's assume I want to target `SQL Server 2016`.

First, I can map `SQL Server 2016` to `13.0` using this page:
https://support.microsoft.com/en-us/help/321185/how-to-determine-the-version-edition-and-update-level-of-sql-server-an 

Next, I can map `13.0` to `Sql130` using this page:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.model.sqlserverversion

Perhaps the docs and `dotnet template` could include these links. Maybe there's a more direct way to figure this out?

Let me know what you think would be a good resolution :-)

**Comment by jmezach** [comment]
Hmm, yeah, I can understand the difficulty in figuring these things out. I guess I'm just so used to mapping these numbers because I've been working them for a long time, but for newcomers it might not be that easy. Frankly it is mostly a side-effect of how Microsoft versions SQL Server internally.

I guess there's a couple of things we could do here. We could either improve the docs and point people towards those articles so that they can figure out which `SqlServerVersion` they need to put in. Or we need to change the way you specify the `SqlServerVersion` in the project file. We could of course allow users to specify `SQL Server 2016` in the project file and then map that magically to the correct `SqlServerVersion` enum value. Or perhaps using `<SqlServerVersion>13.0</SqlServerVersion>` could be enough and we'll map it to the correct enum value under the hood.

I'm fairly positive though that the existing `.sqlproj` also use these values so that's why I kept it at that so that things are mostly compatible.

**Comment by ErikEJ** [comment]
The readme links directly to SqlServerVersion ...

**Comment by brettrowberry** [comment]
> The readme links directly to SqlServerVersion ...

The second link I shared [SqlServerVersion Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.model.sqlserverversion?view=sql-dacfx-150) is in the README. The first, [How to determine the version, edition, and update level of SQL Server and its components](https://support.microsoft.com/en-us/help/321185/how-to-determine-the-version-edition-and-update-level-of-sql-server-an), is not. I was able to figure it out because I was looking at an existing `sqlproj`.

> Frankly it is mostly a side-effect of how Microsoft versions SQL Server internally.

I can't agree more!

> I guess there's a couple of things we could do here. We could either improve the docs and point people towards those articles so that they can figure out which SqlServerVersion they need to put in. Or we need to change the way you specify the SqlServerVersion in the project file. We could of course allow users to specify SQL Server 2016 in the project file and then map that magically to the correct SqlServerVersion enum value. Or perhaps using <SqlServerVersion>13.0</SqlServerVersion> could be enough and we'll map it to the correct enum value under the hood.

I think it's important to do the same thing as `sqlproj` to avoid confusion, which is what this project does today. I also hesitate to add that maintenance overhead for you. I think improving the docs would be the way to go.
