### ISSUE TITLE
Using this template with .net 5

### ISSUE THREAD

**Issue by poserdonut** [rr-wfm/MSBuild.Sdk.SqlProj#96]
Hi! 

I'm trying to setup a build project for my sql-projects using this template in a .net 5 project. However I'm getting:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The current SDK bundles target framework 'netcoreapp5.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 2.1 or 3.1, or file an issue at https://github.com/jmezach/MSBuild.Sdk.SqlProj/ to add support.	Databas.Build	C:\Users\FJBE85\.nuget\packages\msbuild.sdk.sqlproj\1.1.0\Sdk\Sdk.targets	102	
```

Is there an update planned that will work with .net 5?

**Comment by ErikEJ** [comment]
Please share your csproj - it is "net5.0" btw

**Comment by poserdonut** [comment]
It looks like this:
```

<Project Sdk="MSBuild.Sdk.SqlProj/1.9.0">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Database\dbo\**\*.sql" />
  </ItemGroup>

</Project>

```

However it seems it suddenly started working. I don't know why. Sorry to bother you.

**Comment by jmezach** [comment]
@poserdonut The original error message suggests that you were using 1.1.0 of MSBuild.Sdk.SqlProj. That version didn't support .NET 5 yet. We started supporting it in 1.6.0. Your second project file is using 1.9.0, so that's probably why it is working for you now.

That being said, we should probably upgrade our CI pipeline to use the stable .NET 5 release now that it is out ;).
